name: AWS Heartbeat

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 5'

permissions:
  id-token: write
  contents: read

jobs:
  heartbeat:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v5

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v5
        with:
          role-to-assume: ${{ secrets.AWS_HEARTBEAT_ROLE }}
          aws-region: us-east-2

      - name: AWS STS Get Caller Identity
        run: aws sts get-caller-identity
